# Generated by Django 2.2.6 on 2020-04-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Coverpictures',
            fields=[
                ('picid', models.AutoField(db_column='PicID', primary_key=True, serialize=False)),
                ('picture', models.CharField(blank=True, db_column='Picture', max_length=45, null=True)),
            ],
            options={
                'db_table': 'coverpictures',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('customerid', models.AutoField(db_column='customerID', primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, db_column='First Name', max_length=45, null=True)),
                ('last_name', models.CharField(blank=True, db_column='Last Name', max_length=45, null=True)),
                ('phone_field', models.CharField(blank=True, db_column='Phone#', max_length=45, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=45, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=45, null=True)),
                ('registered', models.IntegerField(blank=True, null=True)),
                ('promotions', models.IntegerField(blank=True, null=True)),
                ('password', models.CharField(blank=True, db_column='Password', max_length=45, null=True)),
                ('admin', models.IntegerField(blank=True, db_column='Admin', null=True)),
            ],
            options={
                'db_table': 'customers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('bookid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=45, null=True)),
                ('authors', models.CharField(blank=True, max_length=45, null=True)),
                ('buyprice', models.DecimalField(blank=True, db_column='BuyPrice', decimal_places=2, max_digits=6, null=True)),
                ('sell_price', models.DecimalField(blank=True, db_column='Sell Price', decimal_places=2, max_digits=6, null=True)),
                ('minumum', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=45, null=True)),
                ('number_of_copies', models.IntegerField(blank=True, db_column='number of copies', null=True)),
                ('publisher', models.CharField(blank=True, max_length=45, null=True)),
                ('editor', models.CharField(blank=True, max_length=45, null=True)),
                ('isbn', models.CharField(blank=True, db_column='ISBN', max_length=45, null=True)),
                ('datepublished', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inventory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('orderid', models.AutoField(db_column='OrderID', primary_key=True, serialize=False)),
                ('ordertime', models.TimeField()),
                ('orderdate', models.DateField(blank=True, db_column='OrderDate', null=True)),
                ('orderstatus', models.CharField(blank=True, db_column='OrderStatus', max_length=45, null=True)),
                ('totalprice', models.DecimalField(blank=True, db_column='TotalPrice', decimal_places=2, max_digits=10, null=True)),
                ('shipaddress', models.CharField(blank=True, db_column='ShipAddress', max_length=45, null=True)),
                ('paymentmethod', models.CharField(blank=True, db_column='PaymentMethod', max_length=45, null=True)),
                ('books', models.CharField(blank=True, db_column='Books', max_length=45, null=True)),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Passwords',
            fields=[
                ('passid', models.AutoField(db_column='PassID', primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, db_column='Password', max_length=45, null=True)),
            ],
            options={
                'db_table': 'passwords',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('paymentid', models.AutoField(db_column='PaymentID', primary_key=True, serialize=False)),
                ('card_number', models.CharField(blank=True, db_column='Card number', max_length=45, null=True)),
            ],
            options={
                'db_table': 'payment info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Promotions',
            fields=[
                ('promoid', models.AutoField(db_column='PromoID', primary_key=True, serialize=False)),
                ('promocode', models.CharField(blank=True, db_column='PromoCode', max_length=10, null=True)),
                ('percentage', models.IntegerField(blank=True, db_column='Percentage', null=True)),
                ('start_date', models.DateField(blank=True, db_column='Start Date', null=True)),
                ('expiration_date', models.DateField(blank=True, db_column='Expiration Date', null=True)),
            ],
            options={
                'db_table': 'promotions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('cartid', models.AutoField(db_column='cartID', primary_key=True, serialize=False)),
                ('custid', models.IntegerField(blank=True, db_column='CustID', null=True)),
                ('books', models.CharField(blank=True, db_column='Books', max_length=45, null=True)),
            ],
            options={
                'db_table': 'shopping cart',
                'managed': False,
            },
        ),
    ]
