# Generated by Django 2.2.6 on 2020-04-14 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Passwords',
        ),
    ]
