# Generated by Django 2.2.12 on 2020-04-16 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0002_delete_passwords'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='authuser',
            table='customers',
        ),
    ]
