# Generated by Django 2.2.12 on 2020-04-16 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0003_auto_20200416_1322'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='authuser',
            table='auth_user',
        ),
    ]
