# Generated by Django 2.2.6 on 2020-04-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0004_auto_20200416_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookid', models.AutoField(db_column='bookid', primary_key=True, serialize=False)),
                ('cartid', models.IntegerField(blank=True, db_column='cartid', null=True)),
                ('invid', models.IntegerField(blank=True, db_column='inv', null=True)),
            ],
            options={
                'db_table': 'books',
                'managed': False,
            },
        ),
    ]
