# Generated by Django 2.2.6 on 2020-04-25 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0005_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
